print("Mad Libs Game: A Day at the Beach")
print("Read the following Story: ")
print("Today, my family and I went to the beach. It was a/an (1) day. The sky was (2) and there wasn't a single (3) in sight.")
print("We brought our (4) with us and spread it out on the sand next to a bunch of (5) .")
print("First, we played a game of (6) . Then, we built some (7) .in the sand. It was tiring, so we spent the next hour (8) and (9) in the ocean.")
print("After that, we collected some (10) and put them in a (11) .")
print("On our way back, we saw a big (12) .It was so tall it almost touched my (13) ! ")
print("Before heading home, we stopped by a (14) for some ice cream. It was a/an (15) way to end a/an (16) day at the beach.")
print("Overall, we had (17) fun-filled hours and collected (18) wonderful memories.")
print("\nInstructions: Fill in the blanks with requested parts of speech.\n")
print("1.Adj\n2.Adj\n3.Noun\n4.Noun\n5.Plural Noun\n6.Game\n7.Plural Noun\n8.Verb ending in 'ing'\n9.Verb ending in 'ing'\n10.Plural Noun\n11.Noun\n12.Plant\n13.Part of the body\n14.Place\n15.Verb ending in 'ing'\n16.Adj\n17.Number\n18.Plural Noun\n\n")

Adj1 = input("Enter a Adjective (1): ")
Adj2 = input("Enter a Adjective (2): ")
Noun3 = input("Enter a Noun (3): ")
Noun4 = input("Enter a Noun (4): ")
Plural_Noun5 = input("Enter a Plural Noun (5): ")
Game6 = input("Enter a Game (6): ")
Plural_Noun7 = input("Enter a Plural Noun (7): ")
Verb_ing8 = input("Enter a Verb ending in 'ing' (8): ")
Verb_ing9 = input("Enter a Verb ending in 'ing' (9): ")
Plural_Noun10 = input("Enter a Plural Noun (10): ")
Noun11 = input("Enter a Noun (11): ")
Plant12 = input("Enter a Plant (12): ")
Part_of_body13 = input("Enter a Part of Body (13): ")
Place14 = input("Enter a Place (14): ")
Verb_ing15 = input("Enter a Verb ending in 'ing' (15): ")
Adj16 = input("Enter a Adjective (16): ")
Number17 = input("Enter a Number (17): ")
Plural_Noun18 = input("Enter a Plural Noun (18): \n")


print("Today, my family and I went to the beach. It was a/an (1) "+Adj1+" day. The sky was (2) "+Adj2+" and there wasn't a single (3) "+Noun3+" in sight.")
print("We brought our (4) "+Noun4+" with us and spread it out on the sand next to a bunch of (5) "+Plural_Noun5+" .")
print("First, we played a game of (6) "+Game6+" . Then, we built some (7) "+Plural_Noun7+" in the sand. It was tiring, so we spent the next hour (8) "+Verb_ing8+" and (9) "+Verb_ing9+" in the ocean.")
print("After that, we collected some (10) "+Plural_Noun10+" and put them in a (11) "+Noun11+" .")
print("On our way back, we saw a big (12) "+Plant12+" .It was so tall it almost touched my (13) "+Part_of_body13+" ! ")
print("Before heading home, we stopped by a (14) "+Place14+" for some ice cream. It was a/an (15) "+Verb_ing15+" way to end a/an (16) "+Adj16+" day at the beach.")
print("Overall, we had (17) "+Number17+" fun-filled hours and collected (18) "+Plural_Noun18+" wonderful memories.")
